"""cinema field name update

Revision ID: f074d107d0b4
Revises: 2657a3a43150
Create Date: 2024-04-14 00:04:45.950717

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f074d107d0b4"
down_revision: Union[str, None] = "2657a3a43150"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cinema", sa.Column("address", sa.String(), nullable=True))
    op.drop_column("cinema", "addres")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cinema",
        sa.Column("addres", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("cinema", "address")
    # ### end Alembic commands ###
