"""Upgrade user model

Revision ID: b82c6b78eb6e
Revises: 26c43f8751c0
Create Date: 2024-04-08 22:03:27.658017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b82c6b78eb6e'
down_revision: Union[str, None] = '26c43f8751c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_picture_url')
    op.drop_column('user', 'date_of_birth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('profile_picture_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
